{% set name = "webob" %}
{% set version = "1.8.9" %}
{% set sha256 = "ad6078e2edb6766d1334ec3dee072ac6a7f95b1e32ce10def8ff7f0f02d56589" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
    - legacy-cgi >=2.6

  run:
    - python >=3.8
    - legacy-cgi >=2.6

test:
  imports:
    - webob

about:
  home: http://webob.org/
  license: MIT
  license_family: MIT
  license_file: docs/license.txt
  summary: WSGI request and response object
  description: |
    WebOb provides objects for HTTP requests and responses. Specifically it
    does this by wrapping the WSGI request environment and response
    status/headers/app_iter(body). The request and response objects provide
    many conveniences for parsing HTTP request and forming HTTP responses. Both
    objects are read/write: as a result, WebOb is also a nice way to create HTTP
    requests and parse HTTP responses.
  doc_url: http://webob.readthedocs.org/
  dev_url: https://github.com/Pylons/webob/
  doc_source_url: https://github.com/Pylons/webob/blob/master/docs/index.txt

extra:
  recipe-maintainers:
    - stuertz
    - ChrisBarker-NOAA
